# Generated by Django 2.2.6 on 2019-11-02 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaireName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='questionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionTypeName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.IntegerField()),
                ('age', models.IntegerField()),
                ('diagnosis', models.IntegerField()),
                ('income', models.IntegerField()),
                ('education', models.IntegerField()),
                ('ethnicity', models.IntegerField()),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='questionTypeOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerTypeID', models.IntegerField()),
                ('textRef', models.CharField(max_length=100)),
                ('progRef', models.IntegerField()),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.questionType')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(max_length=200)),
                ('questionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.questionType')),
                ('questionnaireID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='questionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('answer', models.IntegerField()),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.QuestionnaireQuestion')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
