# Generated by Django 2.2.6 on 2019-11-02 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191102_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerType',
            fields=[
                ('answerTypeID', models.IntegerField(primary_key=True, serialize=False)),
                ('textRef', models.CharField(max_length=100)),
                ('progRef', models.IntegerField()),
                ('questionTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.QuestionType')),
            ],
        ),
        migrations.RenameModel(
            old_name='questionAnswer',
            new_name='Answers',
        ),
        migrations.RenameModel(
            old_name='QuestionnaireQuestion',
            new_name='Question',
        ),
        migrations.AlterField(
            model_name='question',
            name='questionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.QuestionType'),
        ),
        migrations.DeleteModel(
            name='questionTypeOptions',
        ),
    ]
