# Generated by Django 2.2.6 on 2019-11-02 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191102_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertype',
            name='questionTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.QuestionType'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.QuestionType'),
        ),
    ]
