# Generated by Django 2.2.6 on 2019-11-02 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191102_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertype',
            name='questionTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.QuestionType'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.QuestionType'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='diagnosis',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='ethnicity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='income',
            field=models.CharField(max_length=100),
        ),
    ]
