# Generated by Django 2.2.6 on 2019-11-02 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20191102_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='userID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answertype',
            name='questionTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.QuestionType'),
        ),
    ]
