# Generated by Django 2.2.6 on 2019-11-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20191102_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertype',
            name='questionTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.QuestionType'),
        ),
    ]
